apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preflight-trigger
spec:
  params:
    - default: '4.8'
      name: ocp_version
      type: string
    - default: trace
      name: log_level
      type: string
    - name: bundle_index_image
      type: string
    - name: bundle_image
      type: string
    - name: asset_type
      type: string
  steps:
    - image: registry.access.redhat.com/ubi8/go-toolset
      name: clone-for-configs
      resources: {}
      script: |
        #!/usr/bin/env bash
        echo "Cloning https://github.com/openshift/release"
        git clone https://github.com/openshift/release
    - args:
        - '-job-name'
        - >-
          periodic-ci-redhat-openshift-ecosystem-preflight-ocp-$(params.ocp_version)-preflight-common-claim
        - '-job-config-path'
        - >-
          release/ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-$(params.ocp_version)-periodics.yaml
        - '-prow-config-path'
        - release/core-services/prow/02_config/_config.yaml
        - '-ocp-version'
        - $(params.ocp_version)
        - '-pflt-artifacts'
        - '${ARTIFACT_DIR}'
        - '-pflt-log-level'
        - $(params.log_level)
        - '-pflt-index-image'
        - $(params.bundle_index_image)
        - '-test-asset'
        - $(params.bundle_image)
        - '-asset-type'
        - $(params.asset_type)
        - '-output-path'
        - preflight-output.json
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/kubeconfig
      image: quay.io/opdev/preflight-trigger
      name: create-prowjob
      resources: {}
  results:
    - name: log_output_file
    - name: result_output_file
    - name: artifacts_output_dir
  workspaces:
    - description: A kubernetes config for the cluster used in preflight testing
      name: kubeconfig
